build: try to fix circleci ci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,10 +12,24 @@ aliases:
     run:
       name: Install pnpm
       command: |
-        curl -fsSL https://get.pnpm.io/install.sh | sh -
+        PNPM_VERSION=$(node -p "require('./package.json').packageManager.match(/^pnpm@(.+)$/)?.[1]")
+
+        if [ -z "$PNPM_VERSION" ]; then
+          echo "ERROR: package.json must contain packageManager: pnpm@<version>"
+          exit 1
+        fi
+
+        echo "Installing pnpm $PNPM_VERSION"
+
+        curl -fsSL https://get.pnpm.io/install.sh | \
+          env PNPM_VERSION="$PNPM_VERSION" SHELL=/bin/bash ENV="$HOME/.bashrc" bash -
+
         echo 'export PNPM_HOME="$HOME/.local/share/pnpm"' >> "$BASH_ENV"
         echo 'export PATH="$PNPM_HOME:$PATH"' >> "$BASH_ENV"
-        source "$BASH_ENV"
+
+        export PNPM_HOME="$HOME/.local/share/pnpm"
+        export PATH="$PNPM_HOME:$PATH"
+
         pnpm --version
 
   - &install-deps
